### ISSUE TITLE
Unable to find current directory

### ISSUE THREAD

**Issue by hoangcuong2011** [siko1056/GNU-Octave-enable-64#7] opened 2017-08-29 12:38 UTC
Hi,

I follow the instructions you gave and compile the code. Everything went smooth until the very end moment with the error: "unable to find current directory"
It is really pity as I almost succeed to build GNU-Octave with enable-64.

Do you know why the error happen? and How to fix the problem?

Thanks!

Best,

....

make[5]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
make[4]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
make[3]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
make[2]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
make[1]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
preserving existing HG-ID file
make[1]: Entering directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
make  check-recursive
preserving existing HG-ID file
make[2]: Entering directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
Making check in libgnu
make[3]: Entering directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/libgnu'
make  check-recursive
make[4]: Entering directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/libgnu'
make[5]: Entering directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/libgnu'
make[5]: Nothing to be done for `check-am'.
make[5]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/libgnu'
make[4]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/libgnu'
make[3]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/libgnu'
preserving existing HG-ID file
make[3]: Entering directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'

Octave successfully built.  Now choose from the following:

   ./run-octave    - to run in place to test before installing
   make check      - to run the tests
   make install    - to install (PREFIX=/home/hoangc/keras-gp-master/GNU-Octave-enable-64/install)

   HG ID for this build is "1327ea4f5a93"

make  check-local
preserving existing HG-ID file
make[4]: Entering directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
cd test && /bin/bash ../run-octave  --norc --silent --no-history /home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/test/fntests.m /home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/test
fatal: unable to find current directory
make[4]: *** [check-local] Error 1
make[4]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'
make[3]: *** [check-am] Error 2
make[3]: Leaving directory `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave'

**Comment by siko1056** [comment] 2017-08-29 13:18
Thank you for your report.  I think Octave has been built.  What I don't know is whether it stopped at `make install` or at `make check`.  Therefore, can you tell me if you can start the build via:

```
/home/hoangc/keras-gp-master/GNU-Octave-enable-64/install/bin/octave
```

**Comment by hoangcuong2011** [comment] 2017-08-30 05:59
Thank you @siko1056 for your quick response.

Running the command gives me the same result: 

fatal: unable to find current directory

I should note that my current OS is: Ubuntu 14.04.4 LTS. Meanwhile, I can confirm that I did okay (build the software) with Ubuntu 16.04

Any idea how to fix the problem?

Thanks!

**Comment by siko1056** [comment] 2017-08-30 08:43
@hoangcuong2011, I just rebuild the whole project from scratch and cannot reproduce your error using openSUSE Leap 42.3. To help you, I need some more information.

1. You can get GNU-Octave-enable-64 to run using Ubuntu 16.04, but not using Ubuntu 14.04.4 LTS?
2. Can you build the Octave sources without errors (not using my repository) on the respective Ubuntu versions?
3. Can you start Octave using the uninstalled version
   ```
   /home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/run-octave
   ```
4. What is the content of the folders:
   - `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/install/bin`
   - `/home/hoangc/keras-gp-master/GNU-Octave-enable-64/build/octave/test`
5. I really cannot figure out which program sends out this error message `fatal: unable to find current directory`. Is it GNU Make, GNU gcc, bash, Octave? Maybe you can inject some code at https://github.com/siko1056/GNU-Octave-enable-64/blob/20ddd0649fb01d06b7328df61d33d165bbbe70cf/Makefile#L247-L249 to get more information. I imagine something like:
   ```
   cd $(BUILD_DIR)/octave && ./configure $(OCTAVE_CONFIG_FLAGS)
   cd $(BUILD_DIR)/octave && $(MAKE) install
   echo "SO FAR SO GOOD"
   cd $(BUILD_DIR)/octave && $(MAKE) check LD_LIBRARY_PATH='$(INSTALL_DIR)/lib'
   ```

**Comment by hoangcuong2011** [comment] 2017-08-30 08:47
@siko1056 Thanks for your reply. I will give you detailed information soon. 

Here is information of created files after the last command: make -j 25 install

0 mkoctfile           0 octave           0 octave-cli           0 octave-config                                                                                           
1028 mkoctfile-4.2.1   112 octave-4.2.1   120 octave-cli-4.2.1   236 octave-config-4.2.1 

It is totally strange with mkoctfile, octave and octave-cli and octave-config. That explains why I got such an weird error.

**Comment by hoangcuong2011** [comment] 2017-09-19 08:16
hi @siko1056 I think I have fixed the problem by modifying Octave code. Specifically, **octave_getcwd_wrapper**() does not work, as the library link is broken. So I have to use Unix API function **gnulib::getcwd()** instead.

This is painful but an useful experience! Thanks a lot for your help!

**Comment by siko1056** [comment] 2017-09-27 10:18
Thank you @hoangcuong2011 for reporting back. As this problem seems not related to this project, I will close that item.

But regarding the problem with `octave_getcwd_wrapper`, is that a problem worth to file as bug report at https://savannah.gnu.org/bugs/?func=additem&group=octave , so you and potential others will never have to struggle with it again?

No bug report exists so far about `octave_getcwd_wrapper` and as far as I have checked, it is only defined, but never used within Octave. `getcwd` is [quite standard](http://pubs.opengroup.org/onlinepubs/7908799/xsh/getcwd.html) and even [Gnulib does not report errors](https://www.gnu.org/software/gnulib/manual/html_node/unistd_002eh.html) about it.

**Comment by shwetaramdas** [comment] 2020-02-14 00:58
> 
> 
> hi @siko1056 I think I have fixed the problem by modifying Octave code. Specifically, **octave_getcwd_wrapper**() does not work, as the library link is broken. So I have to use Unix API function **gnulib::getcwd()** instead.
> 
> This is painful but an useful experience! Thanks a lot for your help!

Hi @hoangcuong2011 , I am facing the same error. COuld you please tell me which file you modified that piece of code in?

**Comment by siko1056** [comment] 2020-02-14 04:26
@shwetaramdas The affected line must be this one:

https://hg.savannah.gnu.org/hgweb/octave/file/eb46a9f47164/liboctave/wrappers/unistd-wrappers.c#l315

Just edit the file downloaded Octave tarball and maybe at the beginning of that file you should add

    #define GNULIB_NAMESPACE gnulib

to get the [gnulib C++ namespace](https://www.gnu.org/software/gnulib/manual/html_node/A-C_002b_002b-namespace-for-gnulib.html).

But what is special about your system that this happens?  Reading [gnulib's getcwd notes](https://www.gnu.org/software/gnulib/manual/html_node/getcwd.html), I do not see an obvious problem, that is fixed by gnulib for a state of the art Linux system.

**Comment by hoangcuong2011** [comment] 2020-02-19 18:54
@shwetaramdas: I got trouble with this 2 years and a half ago. I indeed could not remember anything ... Very sorry for this.
My impression back then was that this library is a great alternative to Matlab. However we need to tweak a lot to make it work. Plus there is something that we can only do with Matlab, not this library.

**Comment by siko1056** [comment] 2020-02-25 08:30
@shwetaramdas Did you have any success solving the issue?

**Closed as completed** 2020-03-03 01:25 UTC
Labels: invalid
